### ISSUE TITLE
Node Preview gave error

### ISSUE THREAD

**Issue by pokeguardian** [AiSatan/node_wrangler_octane#55]
Blender Octane version 2023.1_28.7.1
Node wrangler version 1.4.1

Pressing Shift+Ctrl+Click on any texture node causing an error message like this:

Python: Traceback (most recent call last):
  File "C:\Users\Samville Studio\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\node_wrangler_octane.py", line 1703, in invoke
    return self.invoke_octane(context, event)
  File "C:\Users\Samville Studio\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\node_wrangler_octane.py", line 1565, in invoke_octane
    output_types = [x.nodetype for x in
TypeError: 'NoneType' object is not iterable

**Comment by AiSatan** [comment]
Hi, can you please try the version from this issue, thanks

https://github.com/AiSatan/node_wrangler_octane/issues/53

**Comment by pokeguardian** [comment]
case closed, the solution is work like a charm. tested on 2 pc. maybe you should push this for the update

**Comment by AiSatan** [comment]
Ok, thanks, I'll make a small release later today, thank you :)
