### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by KennyGdfrd** [AiSatan/node_wrangler_octane#57]
Hi AiSatan,

I am having trouble with installation. I am using BlenderOctane 3.5.
Removing it and restarting blender does not fix it. Appreciate the help.

```python

Traceback (most recent call last):
  File "C:\Program Files\BlenderOctane\3.5\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\31615\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\node_wrangler_octane\__init__.py", line 24, in <module>
    from . import operators
  File "C:\Users\31615\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\node_wrangler_octane\operators.py", line 18, in <module>
    from bpy_extras.node_utils import connect_sockets
ImportError: cannot import name 'connect_sockets' from 'bpy_extras.node_utils' (C:\Program Files\BlenderOctane\3.5\scripts\modules\bpy_extras\node_utils.py)
``` 

Thank you!

**Comment by AiSatan** [comment]
Hi, I will take a look.

meanwhile, please, try an older version, they can suit you better but it has the same features, thanks!

https://github.com/AiSatan/node_wrangler_octane/releases/tag/142

or

https://github.com/AiSatan/node_wrangler_octane/releases/tag/1.2.2

**Comment by KennyGdfrd** [comment]
Thanks 1.4.2 works!
